--- Where the generated extras end up, and how every one of them opens.

local M = {}

--- The banner every generated file starts with, so a reader who finds one of
--- these outside the repository knows where it came from and not to edit it.
---@param comment string The file format's line comment marker.
---@param flavor NightfallFlavor
---@return string[]
function M.header(comment, flavor)
  return {
    string.format("%s nightfall.nvim - the %s flavor", comment, flavor),
    comment .. " Generated by `just extras`, do not edit.",
    "",
  }
end

--- Write `lines` to `path`, creating the directory when it is missing.
---@param path string
---@param lines string[]
function M.write(path, lines)
  vim.fn.mkdir(vim.fs.dirname(path), "p")
  vim.fn.writefile(lines, path)
end

return M
