---@alias NightfallFlavor
--- | "nightfall"
--- | "maron"
--- | "deeper-night"
--- | "nord"
--- | "white-night"

---@class NightfallPalette
---@field bg string
---@field fg string
---@field black string
---@field red string
---@field green string
---@field yellow string
---@field blue string
---@field magenta string
---@field cyan string
---@field white string
---@field orange string
---@field pink string
---@field purple string
---@field teal string
---@field sky string
---@field lime string
---@field brown string
---@field sand string
---@field cream string
---@field gray string
---@field charcoal string
---@field silver string
---@field gold string
---@field rose string
---@field coral string
---@field peach string
---@field lavender string
---@field azure string
---@field navy string
