name: Bug Report
description: Report an issue to help us improve Nightfall.nvim
labels: [bug]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Have you checked the following before reporting this issue?
      options:
        - label: I have searched through the Nightfall.nvim documentation.
          required: true
        - label: I have searched through the existing issues of Nightfall.nvim.
          required: true
        - label: I am on the latest version of Nightfall.nvim.
          required: true

  - type: input
    id: system-version
    validations:
      required: true
    attributes:
      label: Operating System/Version
      placeholder: e.g., NixOS

  - type: input
    id: terminal
    validations:
      required: true
    attributes:
      label: Terminal/GUI
      placeholder: e.g., Alacritty

  - type: textarea
    id: health
    validations:
      required: true
    attributes:
      label: Nightfall.nvim Health Check
      description: Output of `:checkhealth nightfall`
      placeholder: |
        ## Nightfall.nvim
        - Nightfall.nvim Version: 0.1.0
        - Neovim Version: v0.9.5
        - OK: Using stable Neovim >= 0.9.5

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug here.

  - type: textarea
    id: reproduce
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior here.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recordings (e.g., via [Asciinema](https://asciinema.org)) to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Additional context here.
