name: Feature Request
description: Suggest an idea to enhance Nightfall.nvim
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Is Your Feature Related to a Problem?
      description: A clear and concise description of the problem you're experiencing. For example, "I'm always frustrated when [...]"
      placeholder: Describe the problem here.

  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Describe the New Feature
      description: A clear and concise description of the feature you would like to see implemented.
      placeholder: Describe the new feature here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that might help explain the feature request.
      placeholder: Add additional context here.
