-- Generate the themes under `extras/` from the Neovim palettes, so a terminal,
-- a pager and the editor stay in step. Run it with `just extras`; never edit
-- the generated files by hand.

local color = require("nightfall.color")
local config = require("nightfall.config")
local context = require("nightfall.context")
local terminal = require("nightfall.groups.terminal")

--- Write `lines` to `path`, creating the directory when it is missing.
---@param path string
---@param lines string[]
local function write(path, lines)
  vim.fn.mkdir(vim.fs.dirname(path), "p")
  vim.fn.writefile(lines, path)
end

--- The banner every generated file opens with.
---@param comment string The file format's line comment marker.
---@param flavor string
---@return string[]
local function header(comment, flavor)
  return {
    string.format("%s nightfall.nvim - the %s flavor", comment, flavor),
    comment .. " Generated by `just extras`, do not edit.",
    "",
  }
end

--- Alacritty reads a TOML file with one table per color role.
---@param flavor string
---@param c NightfallPalette
---@param accent string
---@return string[]
local function alacritty(flavor, c, accent)
  local ansi = terminal.ansi(c)

  --- One `[colors.<name>]` table holding eight ANSI colors, starting at `from`.
  ---@param name string
  ---@param from integer Index of the first ANSI color to use.
  ---@param fade? number How much of each color to keep. Defaults to all of it.
  ---@return string[]
  local function ansi_table(name, from, fade)
    local names = { "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }
    local lines = { "[colors." .. name .. "]" }

    for offset, key in ipairs(names) do
      local hex = ansi[from + offset - 1]
      lines[#lines + 1] = string.format('%s = "%s"', key, fade and color.darken(hex, fade, c.bg) or hex)
    end

    lines[#lines + 1] = ""
    return lines
  end

  local lines = header("#", flavor)

  vim.list_extend(lines, {
    "[colors.primary]",
    string.format('foreground = "%s"', c.fg),
    string.format('background = "%s"', c.bg),
    string.format('dim_foreground = "%s"', c.silver),
    string.format('bright_foreground = "%s"', c.white),
    "",
    "[colors.cursor]",
    string.format('text = "%s"', c.bg),
    string.format('cursor = "%s"', c.fg),
    "",
    "[colors.vi_mode_cursor]",
    string.format('text = "%s"', c.bg),
    string.format('cursor = "%s"', accent),
    "",
    "[colors.selection]",
    string.format('text = "%s"', c.fg),
    string.format('background = "%s"', c.overlay),
    "",
    "[colors.search]",
    string.format('matches = { foreground = "%s", background = "%s" }', c.black, c.cream),
    string.format('focused_match = { foreground = "%s", background = "%s" }', c.black, c.blue),
    "",
    "[colors.hints]",
    string.format('start = { foreground = "%s", background = "%s" }', c.black, c.cyan),
    string.format('end = { foreground = "%s", background = "%s" }', c.black, c.gold),
    "",
    "[colors.footer_bar]",
    string.format('foreground = "%s"', c.black),
    string.format('background = "%s"', c.blue),
    "",
    "[colors]",
    string.format('line_indicator = { foreground = "%s", background = "%s" }', c.black, c.peach),
    "",
  })

  vim.list_extend(lines, ansi_table("normal", 1))
  vim.list_extend(lines, ansi_table("bright", 9))
  vim.list_extend(lines, ansi_table("dim", 1, 0.75))

  return lines
end

--- lazygit reads a YAML file where every color is a list of one or more values.
---@param flavor string
---@param c NightfallPalette
---@param accent string
---@return string[]
local function lazygit(flavor, c, accent)
  --- A `name:` key followed by its colors, indented under `theme:`.
  ---@param name string
  ---@param values string[]
  ---@return string[]
  local function entry(name, values)
    local lines = { "    " .. name .. ":" }
    for _, value in ipairs(values) do
      lines[#lines + 1] = string.format('      - "%s"', value)
    end
    return lines
  end

  local lines = header("#", flavor)

  vim.list_extend(lines, { "gui:", '  nerdFontsVersion: "3"', "  border: rounded", "  theme:" })
  vim.list_extend(lines, entry("activeBorderColor", { accent, "bold" }))
  vim.list_extend(lines, entry("inactiveBorderColor", { c.border }))
  vim.list_extend(lines, entry("searchingActiveBorderColor", { c.teal }))
  vim.list_extend(lines, entry("optionsTextColor", { c.cyan }))
  vim.list_extend(lines, entry("selectedLineBgColor", { c.overlay }))
  vim.list_extend(lines, entry("inactiveViewSelectedLineBgColor", { c.border }))
  vim.list_extend(lines, entry("defaultFgColor", { c.fg }))
  vim.list_extend(lines, entry("cherryPickedCommitBgColor", { c.bg }))
  vim.list_extend(lines, entry("cherryPickedCommitFgColor", { c.rose }))
  vim.list_extend(lines, entry("markedBaseCommitBgColor", { c.bg }))
  vim.list_extend(lines, entry("markedBaseCommitFgColor", { c.gold }))
  vim.list_extend(lines, entry("unstagedChangesColor", { c.red }))
  vim.list_extend(lines, { "" })

  return lines
end

--- yazi reads a TOML theme split by pane.
---@param flavor string
---@param c NightfallPalette
---@param accent string
---@return string[]
local function yazi(flavor, c, accent)
  local lines = header("#", flavor)

  vim.list_extend(lines, {
    "[mgr]",
    string.format('cwd = { fg = "%s" }', c.cyan),
    string.format('hovered = { fg = "%s", bg = "%s" }', c.fg, c.overlay),
    "preview_hovered = { underline = true }",
    string.format('find_keyword = { fg = "%s", bold = true }', c.gold),
    string.format('find_position = { fg = "%s", bg = "reset", bold = true }', c.magenta),
    string.format('marker_copied = { fg = "%s", bg = "%s" }', c.green, c.green),
    string.format('marker_cut = { fg = "%s", bg = "%s" }', c.red, c.red),
    string.format('marker_marked = { fg = "%s", bg = "%s" }', c.teal, c.teal),
    string.format('marker_selected = { fg = "%s", bg = "%s" }', c.gold, c.gold),
    string.format('tab_active = { fg = "%s", bg = "%s" }', c.black, accent),
    string.format('tab_inactive = { fg = "%s", bg = "%s" }', c.fg, c.overlay),
    "tab_width = 1",
    string.format('count_copied = { fg = "%s", bg = "%s" }', c.black, c.green),
    string.format('count_cut = { fg = "%s", bg = "%s" }', c.black, c.red),
    string.format('count_selected = { fg = "%s", bg = "%s" }', c.black, c.gold),
    'border_symbol = "│"',
    string.format('border_style = { fg = "%s" }', c.border),
    "",
    "[mode]",
    string.format('normal_main = { fg = "%s", bg = "%s", bold = true }', c.black, accent),
    string.format('normal_alt = { fg = "%s", bg = "%s" }', accent, c.overlay),
    string.format('select_main = { fg = "%s", bg = "%s", bold = true }', c.black, c.green),
    string.format('select_alt = { fg = "%s", bg = "%s" }', c.green, c.overlay),
    string.format('unset_main = { fg = "%s", bg = "%s", bold = true }', c.black, c.rose),
    string.format('unset_alt = { fg = "%s", bg = "%s" }', c.rose, c.overlay),
    "",
    "[status]",
    string.format('overall = { fg = "%s", bg = "%s" }', c.fg, c.bg),
    'sep_left = { open = "", close = "" }',
    'sep_right = { open = "", close = "" }',
    string.format('progress_label = { fg = "%s", bold = true }', c.white),
    string.format('progress_normal = { fg = "%s", bg = "%s" }', accent, c.overlay),
    string.format('progress_error = { fg = "%s", bg = "%s" }', c.red, c.overlay),
    "",
    "[pick]",
    string.format('border = { fg = "%s" }', accent),
    string.format('active = { fg = "%s", bold = true }', c.magenta),
    string.format('inactive = { fg = "%s" }', c.fg),
    "",
    "[input]",
    string.format('border = { fg = "%s" }', accent),
    string.format('title = { fg = "%s" }', c.fg),
    string.format('value = { fg = "%s" }', c.fg),
    string.format('selected = { bg = "%s" }', c.overlay),
    "",
    "[confirm]",
    string.format('border = { fg = "%s" }', accent),
    string.format('title = { fg = "%s" }', accent),
    string.format('content = { fg = "%s" }', c.fg),
    string.format('list = { fg = "%s" }', c.cyan),
    string.format('btn_yes = { fg = "%s", bg = "%s" }', c.black, c.green),
    string.format('btn_no = { fg = "%s", bg = "%s" }', c.black, c.red),
    'btn_labels = [ "  Yes  ", "  (N)o  " ]',
    "",
    "[cmp]",
    string.format('border = { fg = "%s" }', accent),
    string.format('active = { fg = "%s", bold = true }', c.magenta),
    string.format('inactive = { fg = "%s" }', c.fg),
    "",
    "[tasks]",
    string.format('border = { fg = "%s" }', accent),
    string.format('title = { fg = "%s" }', c.fg),
    string.format('hovered = { fg = "%s", underline = true }', c.magenta),
    "",
    "[which]",
    "cols = 3",
    string.format('mask = { bg = "%s" }', c.overlay),
    string.format('cand = { fg = "%s" }', c.cyan),
    string.format('rest = { fg = "%s" }', c.gray),
    string.format('desc = { fg = "%s" }', c.magenta),
    'separator = "  "',
    string.format('separator_style = { fg = "%s" }', c.border),
    "",
    "[help]",
    string.format('on = { fg = "%s" }', c.cyan),
    string.format('run = { fg = "%s" }', c.magenta),
    string.format('hovered = { bg = "%s", bold = true }', c.overlay),
    string.format('footer = { fg = "%s", bg = "%s" }', c.fg, c.bg),
    "",
    "[notify]",
    string.format('title_info = { fg = "%s" }', c.green),
    string.format('title_warn = { fg = "%s" }', c.yellow),
    string.format('title_error = { fg = "%s" }', c.red),
    "",
    "[filetype]",
    "rules = [",
    string.format('  { mime = "image/*", fg = "%s" },', c.cyan),
    string.format('  { mime = "{audio,video}/*", fg = "%s" },', c.gold),
    string.format('  { mime = "application/{,g}zip", fg = "%s" },', c.magenta),
    string.format('  { mime = "application/{tar,bzip*,7z-compressed,xz,rar}", fg = "%s" },', c.magenta),
    string.format('  { mime = "application/{pdf,doc,rtf}", fg = "%s" },', c.green),
    string.format('  { name = "*", is = "orphan", bg = "%s" },', c.red),
    string.format('  { name = "*", is = "exec", fg = "%s" },', c.green),
    string.format('  { name = "*/", fg = "%s" },', accent),
    "]",
    "",
  })

  return lines
end

--- The generators, keyed by the directory they write into.
local targets = {
  { dir = "alacritty", extension = "toml", render = alacritty },
  { dir = "lazygit", extension = "yaml", render = lazygit },
  { dir = "yazi", extension = "toml", render = yazi },
}

for _, flavor in ipairs(require("nightfall.palette").flavors) do
  local ctx = context.new(flavor, config.get())

  for _, target in ipairs(targets) do
    local path = string.format("extras/%s/%s.%s", target.dir, flavor, target.extension)
    write(path, target.render(flavor, ctx.c, ctx.accent))
    print("wrote " .. path)
  end
end
