local M = {}

---@param colors NightfallPalette
function M.get(colors)
  local Options = require("nightfall").Options
  local utils = require("nightfall.utils")
  return {
    MatchWord = { bg = colors.grey, fg = colors.ghost_white },
    MatchParen = { fg = colors.lavender, bg = colors.nord_blue, style = { bold = true } },
    Pmenu = { bg = colors.dark_blue },
    Question = { fg = colors.violet },
    PmenuSbar = { bg = colors.dark_blue },
    PmenuSel = { bg = colors.lavender, fg = colors.black },
    PmenuThumb = { bg = colors.grey },
    CursorLineNr = { fg = colors.ghost_white },
    LineNr = { fg = colors.grey },
    FloatBorder = { fg = colors.grey, bg = colors.background },
    NormalFloat = { bg = utils.darken(colors.background, 0.8) },
    FloatTitle = { fg = colors.foreground, bg = colors.background },
    TabLine = { bg = colors.statusline_bg, fg = colors.foreground },
    TabLineFill = { bg = colors.black },
    TabLineSel = { fg = colors.black, bg = colors.dark_blue },
    StatusLine = { fg = colors.foreground, bg = colors.statusline_bg },
    StatusLineNC = { fg = colors.statusline_bg, bg = colors.statusline_bg },
    Normal = { fg = colors.foreground, bg = Options.transparent and colors.none or colors.background },
    Directory = { fg = colors.turquoise },
    FoldColumn = { fg = colors.light_cyan, bg = colors.dark_blue },
    Folded = { fg = colors.light_grey, bg = colors.dark_navy },
    IncSearch = { fg = colors.dark_blue, bg = colors.violet },
    CurSearch = { bg = colors.violet, fg = colors.dark_blue },
    ModeMsg = { fg = colors.sand },
    Substitute = { fg = colors.dark_blue, bg = colors.violet },
    Search = { fg = colors.dark_blue, bg = colors.peach },
    SpecialKey = { fg = colors.dark_slate_blue },
    Visual = { bg = colors.dark_navy, style = { bold = true } },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = colors.violet },
    WildMenu = { fg = colors.violet, bg = colors.sky },
    Whitespace = { fg = colors.grey },
    Conceal = { fg = colors.grey },
    Cursor = { fg = colors.black, bg = colors.ghost_white },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    NonText = { fg = colors.dark_slate_blue },
    SignColumn = { fg = colors.dark_slate_blue },
    WinSeparator = { fg = colors.dark_slate_blue },
    ColorColumn = { bg = colors.dark_navy },
    CursorColumn = { bg = colors.dark_navy },
    CursorLine = { bg = colors.dark_navy },
    QuickFixLine = { bg = colors.dark_navy, sp = "none" },
    SpellBad = { sp = colors.violet, style = { undercurl = true } },
    SpellLocal = { sp = colors.light_cyan, style = { undercurl = true } },
    SpellCap = { sp = colors.turquoise, style = { undercurl = true } },
    SpellRare = { sp = colors.pink, style = { undercurl = true } },
    healthSuccess = { bg = colors.green, fg = colors.black },
    ErrorMsg = { fg = colors.violet, style = { bold = true, italic = true } },
    VertSplit = { fg = Options.transparent and colors.dark_navy or colors.dark_slate_blue },
    EndOfBuffer = { fg = colors.grey },
    NormalNC = {
      fg = colors.foreground,
      bg = (Options.dim_inactive and utils.darken(colors.background, 0.8))
        or (Options.transparent and colors.none)
        or colors.background,
    },
    NormalSB = { fg = colors.foreground, bg = utils.darken(colors.background, 0.8) },
    WinBar = { link = "StatusLine" },
    WinBarNC = { link = "StatusLineNC" },
    DiffAdd = { bg = colors.green },
    DiffChange = { bg = colors.pale_yellow, fg = colors.black },
    DiffDelete = { bg = colors.red, fg = colors.black },
    DiffText = { bg = colors.ghost_white },
    diffAdded = { fg = colors.green },
    diffRemoved = { fg = colors.red },
    diffChanged = { fg = colors.pale_yellow },
    diffOldFile = { fg = colors.peach },
    diffNewFile = { fg = colors.pink },
    diffFile = { fg = colors.nord_blue },
    diffLine = { fg = colors.light_grey },
    diffIndexLine = { fg = colors.violet },
  }
end

return M
