name: docs
on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    name: Generate help file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Generate docs
        run: make docs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
