name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  lua-language-server:
    name: lua-language-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - run: just deps
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          configpath: .luarc.json
          level: Warning
