name: Quality Assurance
on:
  push:
    branches: [master]
  pull_request:

jobs:
  style:
    name: Stylua Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.21.0

  test:
    name: Test
    strategy:
      matrix:
        version: [0.10.0, 0.9.5]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          wget -q https://github.com/neovim/neovim/releases/download/v${{ matrix.version }}/nvim-linux64.tar.gz
          tar -xf nvim-linux64.tar.gz
          ln -sf $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - name: Install Neovim for MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/v${{ matrix.version }}/nvim-macos-x86_64.tar.gz
          xattr -c ./nvim-macos-arm64.tar.gz
          tar xzf nvim-macos-x86_64.tar.gz
          export nvim=./nvim-macos-x86_64/bin/nvim

      - name: Run tests
        run: make test
