name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-tags: true
          fetch-depth: 0

      - name: Export changelog for current version
        run: ./release_notes.sh

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: .github/RELEASE_NOTES.md
