name: Release Puller

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release Process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-tags: true
          fetch-depth: 0

      - name: Release
        uses: 2giosangmitom/release-puller-action@v1.0.1
