name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nvim
        run: |
          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
          sudo rm -rf /opt/nvim
          sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz

      - name: Run tests
        run: |
          export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
          nvim -l tests/busted.lua --minitest
